class AppText {
  AppText._();

  static String send = "Göndər";
  static String cardTitle =
      'After clicking the "+" sign, the card will look like this';
  static String cardSubtitle =
      'Press the "+" sign to make the plastic card visible';
  static String goPayment = "Payment =>";
  static String topCategories = "Ən yaxşı kateqoriyalar";
  static String personalDescription =
      "Bu sizin şəxsi məlumatlarınızdır, haqqınızda məlumat əldə etməyə kömək edir";
  static String clearAll = "Hamısını sil";
  static String email = "Email adresi";
  static String ppDescription =
      "İndiki şəklinizi çəkin\n və ya seçin və \ninandırın";
  static String fullName = "Tam ad";
  static String yes = "Bəli";
  static String personalInformation = "Personal Informations";
  static String no = "Xeyr";
  static String bestSale = "Ən çox satan";
  static String sale = "Satış";
  static String buy = "Al";
  static String flashSale = "Flash Satış";
  static String edit = "Redaktə et";
  static String orderSummary = "Sifariş Xülasə";
  static String street = "Küçə";
  static String payment = "Ödəniş";
  static String createCard = "Kart yaradın";
  static String phoneNumber = "Telefon nömrəsi";
  static String wshList = "İstək siyahısı";
  static String removedItem = "Element silindi";
  static String seeAll = "Hamısını gör";
  static String shpaddress = "Çatdırılma ünvanı";
  static String promotion = "Promosyon";
  static String off30 = "50% endirim";
  static String timeOut = "Vaxt bitti!";
  static String method = "Kartla ödəniş";
  static String check = "Sifaris Et";
  static String notifications = "Ismarıc";
  static String off25 = "25% endirim";
  static String mostPopular = "Ən məşhur";
  static String notNotifications = "Hələ heç bir bildirişiniz yoxdur";
  static String off10 = "10% endirim";
  static String hello = "Salam";
  static String promotionDescription =
      "0 iştirak haqqı ilə promosyonlar keçirilir";
  static String password = "Şifrə";
  static String shopNow = "Indi al";
  static String creditCard = "Kredit kartları";
  static String cardDate = "05/32";
  static String home = "Ev";
  static String popularity = "70k populyarlıq";
  static String resetPasswordSent = "Parol Sıfırlama E-poçtu Göndərilib";
  static String profile = "Profil";
  static String bag = "Çanta";
  static String resetPassword = "Parolu sıfırlamaq";
  static String settings = "Parametrlər";
  static String fav = "Sevimlilər";
  static String cardNumber = "Kart kodu";
  static String enterCardNumber = "Kart nömrəsini daxil edin";
  static String visa = "Visa";
  static String newPassword = "Yeni Şifrə";
  static String otpAppBar = "OTP Doğrulama";
  static String nameOnCard = "Kart üzərindəki ad";
  static String name = "Ad";
  static String discount = "10% endirim \nQış\nKolleksiya";
  static String discount1 = "25% endirim \nYay\nKolleksiya";
  static String discount2 = "50% endirim \nPayiz\nKolleksiya";
  static String submit = "təsdiq et";
  static String passwordEquality = "Parollar uyğun gəlmir";
  static String anybank = "Anybank";
  static String minimumEight =
      "Şifrə tələb olunan uzunluqda deyil (8+ olmalıdır)";
  static String expDate = "Son istifadə tarixi";
  static String cardCode = "XXX";
  static String cardCVV = "CVV";
  static String pay = "Ödə";
  static String exp = "EXP";
  static String secureCode = "Təhlükəsizlik kod";
  static String price = "Qiymət";
  static String emptyCart =
      "Sizin kartınız boşdur.\nBir neçə element \nəlavə edin.";
  static String search = "Axtar...";
  static String completeYourDetail = "Detallarınızı tamamlayın";
  static String forgotPassword = "Şifrəni unutmusunuz?";
  static String total = "Ümumi:";
  static String subtotal = "Ara cəmi:";
  static String addToCart = "Səbətə əlavə et";
  static String productDetails = "Məhsul təfərrüatları:";
  static String delivery = "Çatdırılma:";
  static String signUp = "SignUp";
  static String myCart = "Mənim Səbətim";
  static String someThingWrong = "Nəsə xəta baş verdi";
  static String continueText = "Davam et";
  static String username = "İstifadəçi adı";
  static String error = "404 NOT FOUND";
  static String back = "Qayıd";
  static String registerAccount = "Hesab Qeydiyyatı";
  static String finish = "Gəlin başlayaq";
  static String enterEmail = "E-poçtu daxil edin...";
  static String enterUserName = "İstifadəçi adını daxil edin...";
  static String enterPassword = "Parol daxil edin...";
  static String enterPhoneNumber = "Telefon nömrəsini daxil edin...";
  static String enterPasswordAgain = "Şifrəni Yenidən daxil edin...";
  static String description = "bir çox endirim kampaniyaları ilə";
  static String register = "Qeydiyyatdan keçin";
  static String submitOrder = "Sifarişi təsdiq edin";
  static String haveAccount = "Artıq hesabınız var?";
  static String haveNotAccount = "Hesabınız yoxdur?";
  static String login = "Daxil ol";
  static String signIn = "Daxil ol";
  static String signInDescription = "Hesabınıza daxil olun";
}
